name: "Pull Request Labeler"
on:
  - pull_request_target
jobs:
  label-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"

